# Generated by Django 4.0 on 2021-12-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trening'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fblink', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telnr', models.CharField(max_length=20)),
                ('other1', models.CharField(blank=True, max_length=200, null=True)),
                ('other2', models.CharField(blank=True, max_length=200, null=True)),
                ('banknr', models.CharField(max_length=100)),
                ('banktitle', models.CharField(max_length=100)),
                ('bankadress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.eventcategory')),
            ],
        ),
    ]
