# Generated by Django 4.0 on 2021-12-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eventcategory_kontakt_wydarzenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='event_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='zapisy_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
