# Generated by Django 4.0.1 on 2022-01-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wydarzenie_event_link_wydarzenie_zapisy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='trening',
            name='rodzaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trainingevent'),
        ),
    ]
