# Generated by Django 4.0.1 on 2022-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trening_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wydarzenie',
            name='event',
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='event_link',
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='zapisy_link',
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='desc1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='desc2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='desc3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='link1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='link2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='link3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
