# Generated by Django 4.0.2 on 2022-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_wydarzenie_event_remove_wydarzenie_event_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc1', models.CharField(max_length=500)),
                ('link1', models.CharField(max_length=500)),
                ('desc2', models.CharField(blank=True, max_length=500, null=True)),
                ('link2', models.CharField(blank=True, max_length=500, null=True)),
                ('desc3', models.CharField(blank=True, max_length=500, null=True)),
                ('link3', models.CharField(blank=True, max_length=500, null=True)),
                ('day', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.RemoveField(
            model_name='galimg',
            name='event',
        ),
        migrations.DeleteModel(
            name='JaIMojePsy',
        ),
        migrations.DeleteModel(
            name='Kontakt',
        ),
        migrations.RemoveField(
            model_name='trening',
            name='rodzaj',
        ),
        migrations.DeleteModel(
            name='Wydarzenie',
        ),
        migrations.DeleteModel(
            name='GalImg',
        ),
        migrations.DeleteModel(
            name='TrainingEvent',
        ),
        migrations.DeleteModel(
            name='Trening',
        ),
    ]
